CREATE TABLE house ( 
    id SERIAL NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    founder VARCHAR(40) NOT NULL 
);

CREATE TABLE class ( 
    id SERIAL NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    teacher VARCHAR(40) NOT NULL 
);

CREATE TABLE wizard ( 
    id SERIAL NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    age INTEGER NOT NULL,
    house INTEGER NOT NULL,
    FOREIGN KEY (house) REFERENCES house (id) ON DELETE CASCADE
);

CREATE TABLE registration (
    id SERIAL NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status ENUM('APPROVED', 'FAILED', 'IN_PROGRESS') NOT NULL,
    wizard INTEGER NOT NULL,
    class INTEGER NOT NULL,
    UNIQUE(wizard, class),
    FOREIGN KEY (wizard) REFERENCES wizard (id) ON DELETE CASCADE,
    FOREIGN KEY (class) REFERENCES class (id) ON DELETE CASCADE
)